// ATLProject1.idl : ATLProject1的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ATLProject1.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(A7293B74-99A0-475C-BDD2-E08707CCCC40),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

